"""attachment table updated

Revision ID: 2e6c0b460bfc
Revises: 4a73beb2c8b8
Create Date: 2026-07-14 09:09:45.646863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e6c0b460bfc'
down_revision: Union[str, Sequence[str], None] = '4a73beb2c8b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('file_name', sa.String(), nullable=False))
    op.add_column('attachments', sa.Column('file_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'file_type')
    op.drop_column('attachments', 'file_name')
    # ### end Alembic commands ###
