"""assessment table updated

Revision ID: 3c598788c96c
Revises: ba5569214b6d
Create Date: 2026-07-15 12:21:58.683702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c598788c96c'
down_revision: Union[str, Sequence[str], None] = 'ba5569214b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('refresh_token')
    op.drop_table('otp_token')
    op.drop_table('users')
    op.add_column('assessment_results', sa.Column('missing_information', sa.Text(), nullable=True))
    op.add_column('assessment_results', sa.Column('recommended_decision', sa.String(), nullable=True))
    op.add_column('assessment_results', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('assessment_results', sa.Column('confidence_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_results', 'confidence_score')
    op.drop_column('assessment_results', 'explanation')
    op.drop_column('assessment_results', 'recommended_decision')
    op.drop_column('assessment_results', 'missing_information')
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.CheckConstraint("role::text = ANY (ARRAY['ADMIN'::character varying, 'ADJUSTER'::character varying, 'CLAIMANT'::character varying]::text[])", name=op.f('users_role_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('uk6dotkott2kjsp8vw4d0m25fb7'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('otp_token',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('otp_token_pkey'))
    )
    op.create_table('refresh_token',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fkjtx87i0jvq2svedphegvdwcuy')),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_token_pkey')),
    sa.UniqueConstraint('token', name=op.f('ukr4k4edos30bx9neoq81mdvwph'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('notifications',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('descriptions', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk9y21adhxn0ayjhfocscqox7bh')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    # ### end Alembic commands ###
