"""attachment table updated

Revision ID: 4a73beb2c8b8
Revises: fa76e2077291
Create Date: 2026-07-13 16:30:07.846491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a73beb2c8b8'
down_revision: Union[str, Sequence[str], None] = 'fa76e2077291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('file_url', sa.String(), nullable=False))
    op.add_column('attachments', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('attachments', 'file_name')
    op.drop_column('attachments', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('attachments', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('attachments', 'uploaded_at')
    op.drop_column('attachments', 'file_url')
    # ### end Alembic commands ###
