"""attachment table updated

Revision ID: 8b718e603e2a
Revises: 317ac74de390
Create Date: 2026-07-13 15:41:14.480331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b718e603e2a'
down_revision: Union[str, Sequence[str], None] = '317ac74de390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attachments_user_id_fkey'), 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('attachments_user_id_fkey'), 'attachments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
