"""attachment table updated

Revision ID: 921c0bda0401
Revises: 2e6c0b460bfc
Create Date: 2026-07-14 09:10:32.978548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921c0bda0401'
down_revision: Union[str, Sequence[str], None] = '2e6c0b460bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('attachments', sa.Column('file_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'file_type')
    op.drop_column('attachments', 'file_name')
    # ### end Alembic commands ###
