"""foreign keys removed table updated

Revision ID: a424153d36d0
Revises: 921c0bda0401
Create Date: 2026-07-14 09:22:11.350727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a424153d36d0'
down_revision: Union[str, Sequence[str], None] = '921c0bda0401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attachments_uploaded_by_fkey'), 'attachments', type_='foreignkey')
    op.drop_constraint(op.f('claims_user_id_fkey'), 'claims', type_='foreignkey')
    op.drop_constraint(op.f('claims_assigned_to_fkey'), 'claims', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('claims_assigned_to_fkey'), 'claims', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(op.f('claims_user_id_fkey'), 'claims', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('attachments_uploaded_by_fkey'), 'attachments', 'users', ['uploaded_by'], ['id'])
    # ### end Alembic commands ###
