"""user table updated

Revision ID: fa76e2077291
Revises: 8b718e603e2a
Create Date: 2026-07-13 16:21:07.678433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa76e2077291'
down_revision: Union[str, Sequence[str], None] = '8b718e603e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'uploaded_at')
    op.add_column('users', sa.Column('policy_details_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('identification_document_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_profile_complete', sa.Boolean(), nullable=True))
    op.alter_column('users', 'contact_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'contact_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('users', 'is_profile_complete')
    op.drop_column('users', 'identification_document_url')
    op.drop_column('users', 'policy_details_url')
    op.add_column('attachments', sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
