from enum import Enum

class ClaimStatus(str, Enum):
    PENDING="PENDING"
    PROCESSING="PROCESSING"
    SUBMITTED="SUBMITTED"
    UNDER_REVIEW="UNDER_REVIEW"
    MORE_INFORMATION_REQUESTED="MORE_INFORMATION_REQUESTED"
    APPROVED="APPROVED"
    DENIED="DENIED"

